### PR TITLE
Interested in PR?

### PR DESCRIPTION
**Pull request by rsnodgrass**
Feel free to ignore!

* added env variable overrides for authentication methods (split them out into separate methods as well for clarity)
* updated docs/.gitignore/project config files
* added --debug option to one of the scripts
* ran isort/pyupgrade/pyrefurb/brunette on .py files

### CODE REVIEW

**Comment by scottmconway** [comment]
Thanks for the contribution! I'm interested in some of your changes, but multiple PRs may be preferred here for code chsnges vs formatting changes.

I currently format my code with `black`, which uses double quotes for strings by default. I don't want to merge changes that use a different set of formatting rules.

I'll make additional comments on this in a few days, but to get it in a more mergable state, please run black and isort on all Python files in the fork.

I saw that the `logging` import moved to the top of the list of imports in one or more files - I'm not sure why that would occur.

**Comment by rsnodgrass** [comment]
I’ll rerun this with black (instead of brunette which is a black fork with configurable single or double quotes).
  
  
  
  
  
  
  

  
  
>

**Comment by rsnodgrass** [comment]
Ok, all formatting changes from brunette have been reverted and just the manual changes are in the PR now. Plus the additional files (docs, simpler example without logging, etc).

**Comment by scottmconway** [comment]
Ok, I have more thoughts on this:

It looks like a decent amount of this PR refactors variable names and changes comments, and another part adds features (makes it a proper module, adds environment variable support, etc).

Again, I think it should be split into multiple PRs. I'm not really keen to accept refactor changes right off the bat, but features are certainly acceptable.

**Pull request closed without merging**
